quiz_app_fr:
    resource: "@TwitAppBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: |en|fr

quiz_user:
    resource: "@TwitUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/user
    requirements:
        _locale: |en|fr
