security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
 
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_USER
 
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
 
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
 
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            oauth:
                resource_owners:
                    twitter:           "/fr/user/check-twitter"
                login_path:        /fr/user/
                failure_path:      /fr/user/
 
                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: my_user_provider
            logout:
                path:           fos_user_security_logout
            anonymous:    true
 
        login:
            pattern:  ^/user/
            security: false
 
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER
 
    access_control:
        - { path: ^/(en|fr)/user/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/user/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr)/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr)/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr)/user/admin/, role: ROLE_ADMIN }