security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^(_(profiler|wdt))/
            security: false
        main:
            pattern: .*
            provider: main
            form_login:

                login_path: fos_user_security_login
                check_path: fos_user_security_check
                csrf_provider: form.csrf_provider
            remember_me:
                key: %secret%
                lifetime: 3000000
                path: /
                domain: ~
            logout:
                path: fos_user_security_logout
                target: /
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/theme/new, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/category/new, role: IS_AUTHENTICATED_REMEMBERED }