Twit\UserBundle\Entity\User:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        twitter_id:
            type: string
            length: 255
            nullable: true
        twitter_access_token:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
